{
 "title": "Cloud Solar Portfolio",
 "tags": [ "cloudsolarportfolio" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "sites",
    "label": "Site",
    "query": "solarfarma, solarfarmb, solarfarmc"
   }
  ]
 },
 "panels": [
  {
   "title": "Portfolio Aggregate Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Current Power Output - A",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select sum(latest) from (select ts, last(poweroutput_kw) as latest, tbname from renewables.solarfarms where site = 'solarfarma' and ts > $from and ts < $to group by site, tbname ) "
    }
   ]
  },
  {
   "title": "Current Power Output - B",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select sum(latest) from (select ts, last(poweroutput_kw) as latest, tbname from renewables.solarfarms where site = 'solarfarmb' and ts > $from and ts < $to group by site, tbname ) "
    }
   ]
  },
  {
   "title": "Current Power Output - C",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select sum(latest) from (select ts, last(poweroutput_kw) as latest, tbname from renewables.solarfarms where site = 'solarfarmc' and ts > $from and ts < $to group by site, tbname ) "
    }
   ]
  },
  {
   "title": "Total Power Output",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "colNameFormatStr": "{{tbname}}",
     "colNameToGroup": "tbname",
     "formatType": "Time series",
     "sql": "select _wstart as tstamp, avg(poweroutput_kw) as avgpo, tbname from renewables.solarfarms where ts > $from and ts < $to partition by tbname interval(5m) order by tbname asc"
    }
   ]
  },
  {
   "title": "Power Output by Farm",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "colNameFormatStr": "{{site}}",
     "colNameToGroup": "site",
     "formatType": "Time series",
     "sql": "select _wstart, (sum(poweroutput_kw)*5)/300 as `Total Power Output`,site from renewables.solarfarms where ts > $from and ts < $to partition by site interval(5m) order by site asc"
    }
   ]
  },
  { "title": "Average Metrics $sites", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "sites" },
  {
   "title": "Ambient Temperature and Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart, avg(ambienttemperature_c) as `Ambient Temp C`, avg(windspeed_mps) as `Wind Speed m/s` from renewables.solarfarms where ts > $from and ts < $to and site = '$sites'  interval(5m)"
    }
   ]
  },
  {
   "title": "Total Voltage by String",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 17 },
   "targets": [
    {
     "colNameFormatStr": "{{string_id}}",
     "colNameToGroup": "string_id",
     "formatType": "Time series",
     "sql": "select _wstart, sum(voltage)/10 as `Total Voltage`,string_id from renewables.solarfarms where ts > $from and ts < $to and site = '$sites' partition by string_id interval(5m) order by string_id asc"
    }
   ]
  },
  {
   "title": "Average Current by String",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 17 },
   "targets": [
    {
     "colNameFormatStr": "{{string_id}}",
     "colNameToGroup": "string_id",
     "formatType": "Time series",
     "sql": "select _wstart, avg(current) as `Average Current`,string_id from renewables.solarfarms where ts > $from and ts < $to and site = '$sites' partition by string_id interval(5m) order by string_id asc"
    }
   ]
  }
 ]
}